apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: appstek
  name: appstek
  labels:
    app: appstek
spec:
  selector:
    matchLabels:
      app: appstek
  template:
    metadata:
      labels:
        app: appstek
        name: appstek
    spec:
      containers:
        - name: appstek
          image: unnagirirao/AppsTek1/appstek
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 8520
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        