apiVersion: v1
kind: Service
metadata:
  namespace: appstek
  labels:
    app: appstek
  name: appstek
spec:
  ports:
  
    - protocol: TCP
      port: 8520
      targetPort: 8520
   
   
  selector:
    app: appstek
  type: ClusterIP
